version: '3.7'

services:
  glue_aws: 
    container_name: glue_aws
    build: 
      context: ./glue_etl_job
    volumes: 
      - ./glue_etl_job:/code


  terraform: 
    image: hashicorp/terraform:latest
    volumes: 
      - ./:/infra
    working_dir: /infra
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
