name: cd

on: 
    push: 
        branches: 
            - master
    pull_request: 
        branches:
            - master

jobs: 
    deploy_terraform: 
        runs-on: ubuntu-latest
        env: 
            AWS_ACCESS_KEY_ID: ${{   secrets.AWS_ACCESS_KEY_ID   }}
            AWS_SECRET_ACCESS_KEY: ${{   secrets.AWS_SECRET_ACCESS_KEY  }}
        steps: 
            - name: chechout repo 
              uses: actions/checkout@v2
            
        
            - name: Init terraform
              run: make infra-init

            - name: Terraform apply 
              run: make infra-apply 
            

            



