name: CD

on: 
# Only trigger, when the build workflow succeeded
    workflow_run:
      workflows: [CI]
      types:
        - completed

jobs: 
    deploy_terraform: 
        runs-on: ubuntu-latest
        env: 
            AWS_ACCESS_KEY_ID: ${{   secrets.AWS_ACCESS_KEY_ID   }}
            AWS_SECRET_ACCESS_KEY: ${{   secrets.AWS_SECRET_ACCESS_KEY  }}
        steps: 
            - name: chechout repo 
              uses: actions/checkout@v2
            
            - name : destroy terraform 
              uses: make infra-down
              
            - name: Init terraform
              run: make infra-init

            - name: Terraform apply 
              run: make infra-apply 
            

            



