name: CI
on: 
  push: 
    branches: 
      - iac_branch
  pull_request: 
    branches: 
      - iac_branch
jobs:
  run-ci-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Spin up containers
        run: make up
      - name: Run CI test
        run: make ci